spring:
  profiles: local
  h2:
    console:
      enabled: true
  localdatasource:
    jdbcUrl: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
---
spring:
  profiles: poc-mysql
  gcpdatasource: 
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: "jdbc:mysql://${HOSTIP}:3306/test"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
  
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
---
